name: Deploy Docker Image

on:
  push:
    branches: [ "main" ]   # Only build & push on main branch pushes

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/messaging_app:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/messaging_app:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/messaging_app:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/messaging_app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/messaging_app:latest